### ISSUE TITLE
Suggestion/Request: Turn on github dependency checking (dependabot)

### ISSUE THREAD

**Issue by darynmitchell** [24Slides/laravel-saml2#14]
Github provides a service to automatically check composer dependencies for possible security vulnerabilities in 3rd party libraries. See [About managing vulnerable dependencies](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-managing-vulnerable-dependencies) for more info.

It's really easy to turn on detection and notification, and optionally automatic version upgrades if you enable the 3rd option too:

https://github.com/24Slides/laravel-saml2/settings/security_analysis
(requires repo admin role)

![image](https://user-images.githubusercontent.com/3178872/131246263-b3724a87-9270-46bc-98c4-0a5c9650c675.png)

**Comment by brezzhnev** [comment]
It's already enabled :)
