### ISSUE TITLE
Redirect users to different routes.

### ISSUE THREAD

**Issue by freekbass** [24Slides/laravel-saml2#19]
After user logged in, I would like to redirect to a specific page. Each user may be redirected to a different page, depending on some settings. There is a method called getIntendedUrl, which I believe is the most correct to use. however I can not identify a function where I can set this information. Does anyone know if there is a way, without having to implement the 'acs' method?

**Comment by Rkallenkoot** [comment]
Try adding the query param `?returnTo=https://hostname.example/foo/bar` to the Initial loginRoute like so: `https://host.example/saml2/123123-123123-uuid/login?returnTo=https://hostname.example/foo/bar`.

This will fill RelayState when the IDP is POST'ing back to your ACS route and your ACS route will fill `$redirectUrl` with the URL from the `returnTo` parameter.

**Comment by brezzhnev** [comment]
@Rkallenkoot tells the truth :)

**Comment by mtx-z** [comment]
@brezzhnev did you manage to get a custom loginRoute per user? As my "loginRoute" is declared in my saml2.php config file, and is not "related" to a Tenant (no uuid). Thanks.
