### ISSUE TITLE
Need Documentation for IDP

### ISSUE THREAD

**Issue by Thavarajan** [24Slides/laravel-saml2#26]
I hope this package was handle IDP also, if so can we get a documentation for how to configure that,  or just add a link in for IDP, AFIK in the readme everything is about SP only, or am I the one understand it wrong

**Comment by brezzhnev** [comment]
This package doesn't cover configuring Identity Providers, there are lots of them. Maybe adding some references to the most common ones, but again, I don't see this as something really valuable, since most people use it to connect third-party Identity Providers, most likely.
