### ISSUE TITLE
Signature validation failed. SAML Response rejected. (Azure SAML)

### ISSUE THREAD

**Issue by coreation** [24Slides/laravel-saml2#46]
Hi everyone,

I've followed everything as explained, but in the end I get "Signature validation failed. SAML Response rejected" back.
The login URL does work, leading me eventually to the "/acs" route, where the error is then returned.

In the config file, I find these back

```
'x509cert' => env('SAML2_SP_CERT_x509',''),
'privateKey' => env('SAML2_SP_CERT_PRIVATEKEY',''),
```

Do they serve any purpose at all? I don't see them coming back in the README.md, but I don't see them being used anywhere in the code either.

I'm following along the example with an Azure AD SAML configuration and posting here because the issue seems to be coming back as a response from Azure itself, meaning I can't start debuggin my or the library's code.

**Comment by coreation** [comment]
My question still remains, it feels like some of the variables in the saml2.php file are never used. My issue was resolved because of Azure's configuration panel being bugged.

Bug 1: The certificate changed for some unknown reason, make sure you triple check the base64 version of the certificate
Bug 2: The "copy to clipboard" buttons are not working sometimes, making it so that it looks like you copied something, but in fact, you haven't. That very confusing for a first time set-up as most of the links are very alike. (OS X - Chrome)
Bug3: The "test sign in" does not work properly if you updated the URLs after the first time. It just keeps using an older URL, making the test flow not representable. Copy paste the login URL yourself in the browser to have a proper test flow.

**Comment by saboya** [comment]
If anyone else runs into this question (as I did), this is how it's used:
The values in the config file are passed directly to the `OneLoginAuth` (which is actually `OneLogin\Saml2\Auth`) constructor here:
https://github.com/24Slides/laravel-saml2/blob/85dadba29a54f624c29d06b9a2ba0f00186cf665/src/OneLoginBuilder.php#L69-L83

In `OneLogin\Saml2\Auth`'s constructor, it instantiates `OneLogin_Saml2_Settings`, and reads the value here:
https://github.com/SAML-Toolkits/php-saml/blob/78bc99cc254ada52eda166744034a8ef8bff949a/lib/Saml2/Settings.php#L455-L460
