### ISSUE TITLE
Target class [saml] does not exist

### ISSUE THREAD

**Issue by pearlbells** [24Slides/laravel-saml2#53]
Hi
Can you please help me fix the above error?

I have followed the documentation and created the tenant and added the middleware checking.

When I try to access the urls I am getting the attached error.

Please advice.

Thanks

Pearl
![snapshot-1675337441376](https://user-images.githubusercontent.com/16117999/216313555-614f0fb4-0a51-44cb-8a66-242d5a405c24.jpg)

**Comment by nanodreams** [comment]
Just in case anyone is facing this issue... it's related to a missing entry within laravel `app/Http/Kernel.php`

As indicated in the documentation, it's needed to create a new entry with the following details (at least at the time of this message).

> protected $middlewareGroups = [
    'web' => [
        ...
    ],
    'api' => [
        ...
    ],
    'saml' => [
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
    ],
