### ISSUE TITLE
How to Change baseUrl config

### ISSUE THREAD

**Issue by TolgaKantarov** [24Slides/laravel-saml2#55]
Hello,

I keep getting this error: 
`{"error":"The response was received at http://localhost/saml2/***/acs instead of https://***.com/***/acs"} `

I noticed this was due to the HTTP_HOST being localhost. I noticed there is config config named baseUrl in the onelogin settings_example.php file that can override the HTTP_HOST in the url generation. Since the packages are in the /vendor folder (which is in .gitignore) if I do some changes in the files they will not be applied in the repo. 

Is there a setting in the published saml config file that can change the baseUrl? How can I achieve this?

Thanks!

**Comment by mtx-z** [comment]
Hello, did you manage to update the baseUrl? Thank you.

**Comment by piep14** [comment]
@mtx-z  @TolgaKantarov 

Hello,

I have the same problem and I haven't found a solution. What did you do? 

Thank you

**Comment by mtx-z** [comment]
@piep14 Hi,
well, I didn't make it work on my localhost. 

Instead, I'm using Auth0 which can provide you with a custom [SAML2 IdP](https://auth0.com/docs/authenticate/protocols/saml/saml-sso-integrations/configure-auth0-saml-identity-provider) for free (with user management, all free). And my Laravel app on a custom domain. 
So I could setup the entire process to test, with multiple IdP.

Do you encounter the issue from you local env?

**Comment by mtx-z** [comment]
Can you check your saml2_tenants table? Also, can you post your error and your saml2 config?

**Comment by piep14** [comment]
Here's the error: 

The response was received at http://xxx/saml2/2365c568-1d1d-410e-88cd-6b85b643da33/acs instead of https://xxx/saml2/2365c568-1d1d-410e-88cd-6b85b643da33/acs

There's a concern about protocol, a priori

**Comment by mtx-z** [comment]
xxx are same domains? So the difference is http:// vs https?

**Comment by piep14** [comment]
Yes, it's just the http/https protocol, but I don't understand how that's possible.

**Comment by piep14** [comment]
@aacotroneo @brezzhnev  an idea ? thx

**Comment by mtx-z** [comment]
Ah yes I added this in my AppServiceProvider boot() method:

`\OneLogin\Saml2\Utils::setSelfProtocol('https');`

My full config is: 

```
 if (config('app.env') !== 'local' && config('app.env') !== 'development') {
            \URL::forceScheme('https');
            \OneLogin\Saml2\Utils::setSelfProtocol('https');
            //\OneLogin\Saml2\Utils::setBaseURL(config('app.url') . '/' . config('saml2.routesPrefix')); //not working
        }
```

**Comment by piep14** [comment]
@mtx-z  Bravo !!! merci énormément.

**Comment by jpcaparas** [comment]
This is what I use on my PHP local development server (which is the default on Laravel Sail) to force `https` schema if running through an `ngrok` proxy or similar:

```php
use OneLogin\Saml2\Utils as Saml2Utils;
[...]
class AppServiceProvider extends ServiceProvider
{
[...]
    public function boot(Request $request): void
    {
        if ($this->isUsingBuiltInServer() && $request->headers->has('x-forwarded-host')) {
            $protocol = $request->headers->get('x-forwarded-proto');
            if ($protocol === 'https') {
                Saml2Utils::setSelfProtocol('https');
                URL::forceScheme($protocol);
            }
        }
    }
    [...]
    private function isUsingBuiltInServer(): bool
    {
        return str_contains($_SERVER['SERVER_SOFTWARE'], 'PHP') &&
            str_contains($_SERVER['SERVER_SOFTWARE'], 'Development Server');
    }
}
```

Hope this helps anyone caught in a rut.

**Comment by dvphucsgt** [comment]
@mtx-z 
it works fine. Thank you :bow
