### ISSUE TITLE
AADSTS700016: Application with identifier '....' was not found in the directory '...'.

### ISSUE THREAD

**Issue by RosiersRobin** [24Slides/laravel-saml2#80]
I'm having trouble here.

When I setup the SSO using the Microsoft Entrada admin center in the enterprise app "Microsoft Entra SAML Toolkit", I can follow all of their setup instructions to access their test website for saml. That works as intended.

Now I have a laravel app, that needs to allow tenants to access our app using the SAML SSO from microsoft.

this is what I entered in the command:

![image](https://github.com/24Slides/laravel-saml2/assets/5263188/d7350d6a-1236-4c18-9175-be16152618bb)

Then I get this:
![image](https://github.com/24Slides/laravel-saml2/assets/5263188/32adc996-66a7-43af-a350-de47141b79a2)

So I then head back to the Basic SAML configuration in Microsoft entrea admin center and modify the settings like so:

![image](https://github.com/24Slides/laravel-saml2/assets/5263188/d2f1fec0-f9b6-4c93-b50d-c939b54f8b31)

At this point I filled in the inputs with the given data from the package.

When I go to the login URL: https://b83d-[uuid].ngrok-free.app/saml/[UUID]/login

I redirect to the microsoft login page, which is really good, but then I login with my account and I see the following error:

![image](https://github.com/24Slides/laravel-saml2/assets/5263188/8d2c4ec9-8de6-4e62-879b-a64f24a8aa90)

Anyone who has an idea what I can do here to resolve this issue? I need to have this working asap, to have users be able to login into our application..

Thanks in advance!

**Comment by vinicioslimer** [comment]
I am facing this problem too. I haven't found any solution yet. You did it?

**Comment by skydudie** [comment]
Hey @RosiersRobin have you added the user you are trying to sign in with to the application that you created in Entra?
![image](https://github.com/24Slides/laravel-saml2/assets/28289296/12ee791a-c547-4293-911a-426240dab568)

**Comment by bonge-ian** [comment]
Hello @RosiersRobin 
Did you manage to solve this?

If so how did you go about it?

**Comment by fadedhero** [comment]
problem is that the default routes used in saml2.php redirect to http instead of https. The only solution I found yet is to overwrite the "entityId", "assertionConsumerService" and "singleLogoutService" with https routes
