### ISSUE TITLE
Authed user and session data not persisting after successful sign in redirect 

### ISSUE THREAD

**Issue by btrsco** [24Slides/laravel-saml2#82]
I am having issues with forcing a user to log in, or even set user data via a session. By the time the user is redirected to the next url, after a successful sign in via the `/saml2/{uuid}/acs` route, the `auth()->user()` returns `null` and my session key `saml2.user` no longer is set. I tried the exact code provided in the readme of this package on a fresh Laravel install with nothing but Breeze installed and I also see this issue there.

I would love some help or clarity on this issue, below you'll find the code I used:

```php
use Slides\Saml2\Events\SignedIn;
use App\Listeners\Saml2\OnSignedInListener;

class EventServiceProvider extends ServiceProvider 
{
    protected $listen = [
       // ...
        SignedIn::class => [
            OnSignedInListener::class,
        ],
    ];
```

```php
class OnSignedInListener
{
    public function handle(SignedIn $event)
    {
        $saml_user = $event->getSaml2User();
        $user = User::where('email', $saml_user->getUserId())->first();

        if (!$user) {
            Log::error('SAML2: User not found');
            return;
        }

        // force user login
        Auth::login($user);
        session()->put('saml2.user', $saml_user);
    }
}
```

This is supposed to redirect to `/dashboard` afterwards, which it does, but then gets redirected to the login page as it fails the `auth` middleware check. I also created a middleware to intercept the `saml2.user` session key, and force the login after that, still same issue. The custom middleware doesn't see the `saml2.user` nor any of the `saml2.error*` keys after the initial `acs` request.

**Comment by btrsco** [comment]
Nevermind, figured it out. Config requires middleware to be set. I feel like this should default to `['web']`. But I reread the readme a few times and realized the language implies it should be set to something, and doesn't assume what should be used.

**Comment by eocreative-ethan** [comment]
> Nevermind, figured it out

Hey, would you mind sharing your resulting code for this? I'm having the exact same issue at the min, but can't seem to figure out what's missing from my middleware group.

**Comment by btrsco** [comment]
I wish I could, I unfortunately don't have access to the codebase I was using this in anymore. But essentially (if I remember correctly) you want to add the `'web'` to the `routesMiddleware` array in the config. Thats what I did to get it to work for me, but sounds like you already did that. I would just suggest to clear config cache or look into other solutions if that doesn't work. 

Sorry I couldn't be of more help.
