### ISSUE TITLE
[BUG] laravel 7.0 not supported

### ISSUE THREAD

**Issue by hanios123** [24Slides/laravel-saml2#9]
please check out the error log when i tried to install your dependency , any idea how to resolve this  ? 
<img width="806" alt="Screen Shot 2021-01-13 at 0 10 22" src="https://user-images.githubusercontent.com/29795863/104385605-da5aaa00-5533-11eb-9f23-ced957481b43.png">
<img width="806" alt="Screen Shot 2021-01-13 at 0 11 29" src="https://user-images.githubusercontent.com/29795863/104385635-e3e41200-5533-11eb-8960-a6627aafb2f1.png">

**Comment by brezzhnev** [comment]
I was able to install the package on a fresh Laravel 7 project without any issues. Not sure why it happens on your end, but closing for now if no one else gets this.
